<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <RootNamespace>MC_Server_Manager_3</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>assets\ikona.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="assets\ikona.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include=".github\ISSUE_TEMPLATE\" />
    <Folder Include=".github\workflows\" />
    <Folder Include="wiki\" />
  </ItemGroup>

</Project>